# Generated by go2rpm 1
%bcond_without check

# https://github.com/BOPOHA/internal-cache-proxy
%global goipath         github.com/BOPOHA/internal-cache-proxy
Version:                0.0.2

%gometa

%global common_description %{expand:
Simple caching proxy for a fast rebuild containers.}

%global golicenses      LICENSE
Name:           %{goname}
Release:        1%{?dist}
Summary:        Simple caching proxy for a fast rebuild containers

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/go-httpproxy/httpproxy)
BuildRequires:  golang(github.com/gregjones/httpcache)
BuildRequires:  golang(github.com/gregjones/httpcache/diskcache)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/internal-cache-proxy %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Apr 01 19:51:24 CEST 2020 Anatolii Vorona <vorona.tolik@gmail.com> - 0.0.2-1
- Initial package

